"""init

Revision ID: 5e4bdd1e901e
Revises: 7cfe604a8b54
Create Date: 2026-03-01 12:03:36.710150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4bdd1e901e'
down_revision: Union[str, Sequence[str], None] = '7cfe604a8b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_url'), 'bookmarks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_url'), 'bookmarks', ['user_id', 'url'])
    # ### end Alembic commands ###
